function ShowCRLB(CRLB)
screen_size = get(0,'ScreenSize');
comparison_window = figure('Name','Calculated Cramer-Rao lower bounds of parameter estimators',...
    'Position',[screen_size(3)*0.35 screen_size(4)*0.35 screen_size(3)*0.3 screen_size(4)*0.3],...
    'NumberTitle','off');

hTextTitle = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.2 0.85 0.6 0.08],...
    'BackgroundColor',[0.8 0.8 0.8],...
    'String','Calculated Cramer-Rao lower bounds of parameter estimators',...
    'FontWeight','bold');

hTextAmplitude = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.6 0.4 0.04],...
    'BackgroundColor',[0.8 0.8 0.8],...
    'String','Amplitude: ',...
    'HorizontalAlignment','left');

hTextPhase = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.5 0.4 0.04],...
    'BackgroundColor',[0.8 0.8 0.8],...
    'String','Initial phase: ',...
    'HorizontalAlignment','left');

hTextDC = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.4 0.4 0.04],...
    'BackgroundColor',[0.8 0.8 0.8],...
    'String','DC component: ',...
    'HorizontalAlignment','left');

hTextFreq = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.3 0.4 0.04],...
    'BackgroundColor',[0.8 0.8 0.8],...
    'String','Frequency: ',...
    'HorizontalAlignment','left');

hTextNoise = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.2 0.4 0.04],...
    'BackgroundColor',[0.8 0.8 0.8],...
    'String','Noise RMS: ',...
    'HorizontalAlignment','left');

hTextAmplitudeVal = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.55 0.6 0.3 0.04],...
    'BackgroundColor',[0.8 0.8 0.8],...
    'String','N/A',...
    'HorizontalAlignment','left');

hTextPhaseVal = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.55 0.5 0.3 0.04],...
    'BackgroundColor',[0.8 0.8 0.8],...
    'String','N/A',...
    'HorizontalAlignment','left');

hTextDCVal = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.55 0.4 0.3 0.04],...
    'BackgroundColor',[0.8 0.8 0.8],...
    'String','N/A',...
    'HorizontalAlignment','left');

hTextFreqVal = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.55 0.3 0.3 0.04],...
    'BackgroundColor',[0.8 0.8 0.8],...
    'String','N/A',...
    'HorizontalAlignment','left');

hTextNoiseVal = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.55 0.2 0.3 0.04],...
    'BackgroundColor',[0.8 0.8 0.8],...
    'String','N/A',...
    'HorizontalAlignment','left');

set(hTextAmplitudeVal,'String',sprintf('%e [LSB]',CRLB.amplitude));
set(hTextPhaseVal,'String',sprintf('%e [DEG]',CRLB.phase));
set(hTextDCVal,'String',sprintf('%e [LSB]',CRLB.C));
set(hTextFreqVal,'String',sprintf('%e [f/fs]',CRLB.theta));
set(hTextNoiseVal,'String',sprintf('%e [LSB]',CRLB.sigma));

end

